[project]
name = "dune-query"
version = "0.1.0"
description = "Querying Dune Analytics using Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dune-client>=1.10.0",
    "pandas>=3.0.0",
    "python-dotenv>=1.2.1",
]
